import{NextRequest,NextResponse}from'next/server'
import{hostAuthorized}from'@/lib/host-api'
import{createAdminClient}from'@/lib/supabase/admin'
import{hasDatabase}from'@/lib/security'
import{getStatistics,statisticKeys,type StatisticKey}from'@/lib/statistics'
export const dynamic='force-dynamic'
const headers={'Cache-Control':'no-store'}
export async function GET(){if(!await hostAuthorized())return NextResponse.json({error:'Unauthorized'},{status:401,headers});if(!hasDatabase())return NextResponse.json({error:'Connect the production database first.'},{status:503,headers});return NextResponse.json(await getStatistics(),{headers})}
export async function PATCH(req:NextRequest){if(!await hostAuthorized())return NextResponse.json({error:'Unauthorized'},{status:401,headers});if(!hasDatabase())return NextResponse.json({error:'Connect the production database first.'},{status:503,headers});try{const b=await req.json(),key=String(b.key)as StatisticKey;if(!statisticKeys.includes(key))return NextResponse.json({error:'Unknown statistic.'},{status:400,headers});const adjustment=Number(b.adjustment),manualOverride=b.useOverride?Number(b.manualOverride):null;if(!Number.isSafeInteger(adjustment)||adjustment< -1_000_000_000||adjustment>1_000_000_000||manualOverride!==null&&(!Number.isSafeInteger(manualOverride)||manualOverride<0))return NextResponse.json({error:'Enter a valid whole number.'},{status:400,headers});const db=createAdminClient();const{data:previous}=await db.from('statistic_adjustments').select('*').eq('statistic_key',key).maybeSingle();const next={statistic_key:key,adjustment,manual_override:manualOverride,updated_at:new Date().toISOString()};const{error}=await db.from('statistic_adjustments').upsert(next,{onConflict:'statistic_key'});if(error)throw error;await db.from('audit_logs').insert({action:'statistics.update',entity_type:'statistic',entity_id:key,previous_value:previous||null,new_value:next});return NextResponse.json(await getStatistics(),{headers})}catch(error){console.error('statistics update failed',error);return NextResponse.json({error:'The number could not be saved.'},{status:500,headers})}}
