import test from'node:test';import assert from'node:assert/strict';import{readFileSync,readdirSync,statSync}from'node:fs';import{join}from'node:path';
const root=process.cwd();function files(dir){return readdirSync(dir).flatMap(n=>{const p=join(dir,n);return statSync(p).isDirectory()?files(p):[p]})}
test('required public routes exist',()=>{for(const p of ['app/page.tsx','app/conversations/page.tsx','app/papers/page.tsx','app/about/page.tsx','app/questions/page.tsx','app/join/page.tsx','app/privacy/page.tsx','app/host/login/page.tsx'])assert.ok(statSync(join(root,p)).isFile())})
test('no phone fields or raw host password variables',()=>{const paths=files(join(root,'app')).concat(files(join(root,'components')),files(join(root,'lib')),files(join(root,'supabase')));const source=paths.filter(p=>/\.(tsx?|sql)$/.test(p)).map(p=>readFileSync(p,'utf8')).join('\n');assert.doesNotMatch(source,/type=["']tel["']|name=["']phone|ADMIN_PASSWORD\b/i)})
test('loading sequence is skippable and motion aware',()=>{const source=readFileSync(join(root,'components/OpeningSequence.tsx'),'utf8')+readFileSync(join(root,'app/globals.css'),'utf8');assert.match(source,/Skip/);assert.match(source,/prefers-reduced-motion/)})
test('opening is an extruded South Korea outline and plays once per session',()=>{const source=readFileSync(join(root,'components/OpeningSequence.tsx'),'utf8')+readFileSync(join(root,'app/globals.css'),'utf8');assert.match(source,/koreaPath/);assert.match(source,/Array\.from\(\{ length: 10 \}/);assert.match(source,/translateZ/);assert.match(source,/kv-intro-seen/)})
test('public brand has no legacy red and uses a centered bridge wordmark',()=>{const css=readFileSync(join(root,'app/globals.css'),'utf8');const nav=readFileSync(join(root,'components/Nav.tsx'),'utf8');assert.doesNotMatch(css,/#a83c2d|var\(--red\)/i);assert.match(css,/left:50%;top:50%;transform:translate\(-50%,-50%\)/);assert.match(nav,/BrandMark/)})
test('analytics writes server-side, refuses false success, and returns live totals',()=>{const route=readFileSync(join(root,'app/api/analytics/route.ts'),'utf8');const beacon=readFileSync(join(root,'components/AnalyticsBeacon.tsx'),'utf8');const home=readFileSync(join(root,'app/page.tsx'),'utf8');assert.match(route,/analytics_events/);assert.match(route,/getStatistics/);assert.match(route,/status:503/);assert.match(route,/prefetch/);assert.match(beacon,/cache:'no-store'/);assert.match(home,/LiveStatistics/);assert.doesNotMatch(home,/sampleTotals/)})
test('host authentication uses a stable server secret and HTTP-only cookie',()=>{const login=readFileSync(join(root,'app/api/host/login/route.ts'),'utf8');const session=readFileSync(join(root,'lib/session.ts'),'utf8');assert.match(login,/verifyHostPassword/);assert.match(login,/authSecretsConfigured/);assert.doesNotMatch(session,/randomBytes/);assert.match(session,/httpOnly:true/);assert.match(session,/secure:process\.env\.NODE_ENV==='production'/);assert.match(session,/sameSite:'strict'/)})
test('host content requires uploadable video and PDF inputs',()=>{const source=readFileSync(join(root,'components/HostContentForm.tsx'),'utf8');assert.match(source,/video\/mp4/);assert.match(source,/application\/pdf/);assert.match(source,/pdfFile[^>]+required/);assert.match(source,/Google Drive/)})
