'use client'
import{useEffect,useState}from'react'
import type{StatisticKey,StatisticsPayload}from'@/lib/statistics'
const labels:Record<StatisticKey,string>={site_impressions:'Site impressions',content_views:'Total content views',reactions:'Total reactions',subscribers:'Total subscribers',conversations:'Published conversations',papers:'Published papers',comments:'Total comments',countries:'Countries reached'}
type Draft={adjustment:number;useOverride:boolean;manualOverride:number}
const makeDrafts=(value:StatisticsPayload)=>Object.fromEntries((Object.keys(labels)as StatisticKey[]).map(key=>[key,{adjustment:value.adjustments[key],useOverride:value.overrides[key]!==null,manualOverride:value.overrides[key]??value.displayed[key]}]))as Record<StatisticKey,Draft>
export default function ByNumbersEditor({initial}:{initial:StatisticsPayload}){
  const[stats,setStats]=useState(initial),[drafts,setDrafts]=useState(()=>makeDrafts(initial)),[dirty,setDirty]=useState<Set<StatisticKey>>(new Set()),[status,setStatus]=useState('')
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.size){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',warn);return()=>removeEventListener('beforeunload',warn)},[dirty])
  async function save(key:StatisticKey,next=drafts[key]){setStatus(`Saving ${labels[key]}…`);const r=await fetch('/api/host/statistics',{method:'PATCH',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,...next})});const data=await r.json();if(!r.ok){setStatus(data.error||'Could not save.');return}setStats(data);setDrafts(current=>({...current,[key]:makeDrafts(data)[key]}));setDirty(current=>{const copy=new Set(current);copy.delete(key);return copy});setStatus(`${labels[key]} saved and updated publicly.`);dispatchEvent(new CustomEvent('kv:stats-changed'))}
  function update(key:StatisticKey,value:Partial<Draft>){setDrafts(d=>({...d,[key]:{...d[key],...value}}));setDirty(current=>new Set(current).add(key))}
  function reset(key:StatisticKey){const next={...drafts[key],adjustment:0,useOverride:false};setDrafts(d=>({...d,[key]:next}));void save(key,next)}
  return <><div className="numbers-editor">{(Object.keys(labels)as StatisticKey[]).map(key=>{const d=drafts[key],calculated=d.useOverride?d.manualOverride:Math.max(0,stats.verified[key]+d.adjustment);return <section className="number-editor" key={key}><header><div><small>Public statistic</small><h2>{labels[key]}</h2></div><strong>{calculated.toLocaleString()}</strong></header><div className="number-fields"><label>Verified system total<input value={stats.verified[key]} readOnly/></label><label>Manual adjustment<input type="number" step="1" value={d.adjustment} onChange={e=>update(key,{adjustment:Number(e.target.value)})}/></label><label>Final public number<input value={calculated} readOnly/></label></div><label className="host-switch"><input type="checkbox" checked={d.useOverride} onChange={e=>update(key,{useOverride:e.target.checked})}/> Use a custom public number</label>{d.useOverride&&<label>Exact public number<input type="number" min="0" step="1" value={d.manualOverride} onChange={e=>update(key,{manualOverride:Number(e.target.value)})}/></label>}<div className="host-actions"><button className="button" onClick={()=>save(key)}>Save {labels[key]}</button><button className="button secondary" onClick={()=>reset(key)}>Reset adjustment</button></div></section>})}</div><p className="host-save-status" role="status" aria-live="polite">{status}</p></>
}
