'use client'
import { FormEvent, useEffect, useState } from 'react'
const reactionTypes=[['appreciate','M6 13h12M12 7v12'],['insightful','M9 18h6M10 22h4M8 11a4 4 0 1 1 8 0c0 2-1 3-2 4H10c-1-1-2-2-2-4Z'],['powerful','m13 2-9 12h7l-1 8 9-12h-7z']]
export default function Interactions({contentId,contentType}:{contentId:string;contentType:'conversation'|'paper'}){
 const [active,setActive]=useState<string[]>([]);const [status,setStatus]=useState('');const [comments,setComments]=useState<Array<{id:string;anonymous_name:string;body:string;created_at:string}>>([])
 useEffect(()=>{fetch(`/api/comments?contentId=${contentId}`).then(r=>r.ok?r.json():[]).then(setComments).catch(()=>{})},[contentId])
 async function react(type:string){const visitorId=localStorage.getItem('kv-visitor')||crypto.randomUUID();localStorage.setItem('kv-visitor',visitorId);const remove=active.includes(type);setActive(a=>remove?a.filter(x=>x!==type):[...a,type]);await fetch('/api/reactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contentId,contentType,type,visitorId})})}
 async function comment(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('Sending…');const body=new FormData(e.currentTarget).get('body');const r=await fetch('/api/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contentId,contentType,body})});const data=await r.json().catch(()=>({}));if(r.ok){setComments(c=>[...c,data]);e.currentTarget.reset();setStatus('Comment published.')}else setStatus(data.error||'Comment could not be published.')}
 return <><div className="interactions"><div><div className="eyebrow">React to this piece</div><div className="reaction-set">{reactionTypes.map(([type,path])=><button key={type} aria-pressed={active.includes(type)} onClick={()=>react(type)}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d={path}/></svg>{type}</button>)}</div></div><button className="text-link" onClick={()=>navigator.share?.({title:document.title,url:location.href})}>Share <span>↗</span></button></div><section className="comment-form"><div className="eyebrow">Comments / {comments.length}</div>{comments.map(c=><article key={c.id}><strong>{c.anonymous_name}</strong><p>{c.body}</p></article>)}<form onSubmit={comment}><label className="sr-only" htmlFor="comment-body">Comment</label><textarea id="comment-body" name="body" required maxLength={1800} placeholder="Add to the conversation"/><button>Publish comment</button><p className="form-status" role="status">{status}</p></form></section></>
}
