'use client'
import{useEffect,useRef,useState,type PointerEvent as ReactPointerEvent}from'react'

type Country={code:string;name:string;lat:number|null;lon:number|null;impressions:number;contentViews:number;hostAdded?:number;total:number;share:number}
type Topology={transform:{scale:[number,number];translate:[number,number]};arcs:number[][][]}
type Point={country:Country;x:number;y:number;z:number}
const rad=Math.PI/180

function decodeArcs(topology:Topology){const{scale,translate}=topology.transform;return topology.arcs.map(arc=>{let x=0,y=0;return arc.map(([dx,dy])=>{x+=dx;y+=dy;return[x*scale[0]+translate[0],y*scale[1]+translate[1]]as[number,number]})})}
function project(lat:number,lon:number,yaw:number,pitch:number,cx:number,cy:number,radius:number){const lambda=(lon+yaw)*rad,phi=lat*rad,p=pitch*rad,x=Math.cos(phi)*Math.sin(lambda),y=Math.sin(phi),z=Math.cos(phi)*Math.cos(lambda),yp=y*Math.cos(p)-z*Math.sin(p),zp=y*Math.sin(p)+z*Math.cos(p);return{x:cx+radius*x,y:cy-radius*yp,z:zp}}

export default function StatisticsGlobe(){
 const[countries,setCountries]=useState<Country[]>([]),[locatedViews,setLocatedViews]=useState(0),[hovered,setHovered]=useState<Country|null>(null),[visible,setVisible]=useState(true),[reduced,setReduced]=useState(false),canvasRef=useRef<HTMLCanvasElement>(null),shellRef=useRef<HTMLDivElement>(null),arcsRef=useRef<Array<Array<[number,number]>>>([]),pointsRef=useRef<Point[]>([]),rotation=useRef({yaw:-24,pitch:-8,vx:0,vy:0}),drag=useRef({active:false,id:-1,x:0,y:0,moved:0}),size=useRef({width:420,height:420})

 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setReduced(media.matches);update();media.addEventListener('change',update);Promise.all([fetch('/api/geography',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()),fetch('/data/countries-110m.json').then(r=>r.ok?r.json():Promise.reject())]).then(([distribution,topology]:[{countries:Country[];totalLocatedViews:number},Topology])=>{setCountries(distribution.countries||[]);setLocatedViews(distribution.totalLocatedViews||0);arcsRef.current=decodeArcs(topology)}).catch(()=>{});const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:.05});if(shellRef.current)observer.observe(shellRef.current);return()=>{media.removeEventListener('change',update);observer.disconnect()}},[])

 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const resize=()=>{const rect=canvas.getBoundingClientRect(),ratio=Math.min(2,devicePixelRatio||1);size.current={width:rect.width,height:rect.height};canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio)};resize();const observer=new ResizeObserver(resize);observer.observe(canvas);return()=>observer.disconnect()},[])

 useEffect(()=>{let frame=0,last=performance.now();const draw=(now:number)=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const{width,height}=size.current,ratio=canvas.width/Math.max(1,width),cx=width/2,cy=height/2,radius=Math.min(width,height)*.37;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,width,height);if(visible&&!drag.current.active&&!reduced){const dt=Math.min(40,now-last);rotation.current.yaw+=.006*dt+rotation.current.vx*dt;rotation.current.pitch=Math.max(-32,Math.min(32,rotation.current.pitch+rotation.current.vy*dt));const decay=Math.pow(.9,dt/16.67);rotation.current.vx*=decay;rotation.current.vy*=decay}last=now;const globe=ctx.createRadialGradient(cx-radius*.32,cy-radius*.36,radius*.04,cx,cy,radius);globe.addColorStop(0,'#d9e0e728');globe.addColorStop(.58,'#2d4a6824');globe.addColorStop(1,'#05070b9a');ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.fillStyle=globe;ctx.fill();ctx.strokeStyle='#d9e0e7c7';ctx.lineWidth=1.25;ctx.stroke();ctx.save();ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.clip();const line=(coordinates:Array<[number,number]>,color:string,widthValue:number)=>{ctx.beginPath();let pen=false;for(const[lon,lat]of coordinates){const p=project(lat,lon,rotation.current.yaw,rotation.current.pitch,cx,cy,radius);if(p.z<=0){pen=false;continue}if(!pen){ctx.moveTo(p.x,p.y);pen=true}else ctx.lineTo(p.x,p.y)}ctx.strokeStyle=color;ctx.lineWidth=widthValue;ctx.stroke()};for(let lon=-150;lon<=180;lon+=30)line(Array.from({length:73},(_,i)=>[lon,-90+i*2.5]as[number,number]),'#71869b32',.6);for(let lat=-60;lat<=60;lat+=30)line(Array.from({length:145},(_,i)=>[-180+i*2.5,lat]as[number,number]),'#71869b32',.6);for(const arc of arcsRef.current)line(arc,'#b9c5d08e',.72);ctx.restore();pointsRef.current=[];for(const country of countries){if(country.lat===null||country.lon===null)continue;const p=project(country.lat,country.lon,rotation.current.yaw,rotation.current.pitch,cx,cy,radius);if(p.z<=0)continue;const dot=4+Math.sqrt(country.share)*11;ctx.beginPath();ctx.arc(p.x,p.y,dot,0,Math.PI*2);ctx.fillStyle='#eef2f5';ctx.shadowColor='#9babbc';ctx.shadowBlur=13;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#2d4a68';ctx.lineWidth=2;ctx.stroke();pointsRef.current.push({country,...p})}if(visible&&!reduced)frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame)},[countries,reduced,visible])

 const down=(event:ReactPointerEvent<HTMLCanvasElement>)=>{if(event.button!==0)return;event.currentTarget.setPointerCapture(event.pointerId);drag.current={active:true,id:event.pointerId,x:event.clientX,y:event.clientY,moved:0};rotation.current.vx=0;rotation.current.vy=0;event.currentTarget.classList.add('is-dragging')}
 const move=(event:ReactPointerEvent<HTMLCanvasElement>)=>{const box=event.currentTarget.getBoundingClientRect(),localX=event.clientX-box.left,localY=event.clientY-box.top;if(!drag.current.active){const hit=pointsRef.current.find(point=>Math.hypot(point.x-localX,point.y-localY)<13);setHovered(hit?.country||null);return}event.preventDefault();const dx=event.clientX-drag.current.x,dy=event.clientY-drag.current.y;rotation.current.yaw+=dx*.28;rotation.current.pitch=Math.max(-32,Math.min(32,rotation.current.pitch-dy*.2));rotation.current.vx=Math.max(-.13,Math.min(.13,dx*.012));rotation.current.vy=Math.max(-.07,Math.min(.07,-dy*.009));drag.current.x=event.clientX;drag.current.y=event.clientY;drag.current.moved+=Math.hypot(dx,dy)}
 const up=(event:ReactPointerEvent<HTMLCanvasElement>)=>{if(!drag.current.active||drag.current.id!==event.pointerId)return;drag.current.active=false;event.currentTarget.classList.remove('is-dragging');if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId)}

 return <div ref={shellRef} className="globe-shell globe-data-shell"><div className="globe-meta"><span>Listener geography</span><strong>{countries.length.toLocaleString()} {countries.length===1?'country':'countries'} reached</strong></div><div className="globe-canvas-wrap"><canvas ref={canvasRef} className="globe-canvas" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onPointerLeave={()=>{if(!drag.current.active)setHovered(null)}} role="img" aria-label={countries.length?`Interactive world globe. Located viewing activity: ${countries.map(country=>`${country.name}, ${country.total}`).join('; ')}`:'Interactive world globe with no located activity yet.'}/>{hovered&&<div className="globe-tooltip"><strong>{hovered.name}</strong><span>{hovered.total.toLocaleString()} located {hovered.total===1?'view':'views'} · {(hovered.share*100).toFixed(1)}%</span></div>}</div><div className="country-distribution"><header><span>View distribution</span><small>{locatedViews.toLocaleString()} located views</small></header>{countries.length?<ol>{countries.map(country=><li key={country.code}><span><b>{country.name}</b><small>{country.impressions} visits · {country.contentViews} content views{country.hostAdded?` · ${country.hostAdded} host-added`:''}</small></span><i><em style={{width:`${Math.max(2,country.share*100)}%`}}/></i><strong>{(country.share*100).toFixed(country.share<.1?1:0)}%</strong></li>)}</ol>:<p>No country distribution is shown until located analytics or host-added listens exist.</p>}</div><p>Country outlines use Natural Earth public-domain boundaries. Locations combine privacy-respecting analytics with clearly identified host-added listens.</p></div>
}
