import{NextRequest,NextResponse}from'next/server'
import{hostAuthorized}from'@/lib/host-api'
import{cleanText,hasDatabase}from'@/lib/security'
import{createAdminClient}from'@/lib/supabase/admin'
export const dynamic='force-dynamic';export const revalidate=0
const statuses=new Set(['draft','scheduled','published','unpublished','archived'])
const headers={'Cache-Control':'private, no-store, max-age=0'}
const text=(value:unknown,max=20000)=>cleanText(value,max)||null
const date=(value:unknown)=>{const raw=cleanText(value,50);return raw&&!Number.isNaN(Date.parse(raw))?new Date(raw).toISOString():null}
const integer=(value:unknown)=>{const n=Number(value);return Number.isFinite(n)?Math.trunc(n):null}
const lines=(value:unknown)=>cleanText(value,30000).split('\n').map(v=>v.trim()).filter(Boolean)
const bool=(value:unknown)=>value===true||value==='true'||value==='on'
function source(url:string,requested:string){if(requested==='upload')return'upload';if(/drive\.google\.com/i.test(url))return'drive';if(/youtu(?:\.be|be\.com)/i.test(url))return'youtube';if(/vimeo\.com/i.test(url))return'vimeo';return'supabase'}
function build(type:'conversation'|'paper',b:Record<string,unknown>){
 const status=statuses.has(String(b.status))?b.status:'draft',published=date(b.published_at)||(status==='published'?new Date().toISOString():null)
 const common={slug:text(b.slug,180),title:text(b.title,180),status,published_at:published,display_date:date(b.display_date)||published,scheduled_for:date(b.scheduled_for),comments_enabled:bool(b.comments_enabled),reactions_enabled:bool(b.reactions_enabled),view_adjustment:integer(b.view_adjustment)||0,reaction_adjustment:integer(b.reaction_adjustment)||0,featured:bool(b.featured),homepage_visible:bool(b.homepage_visible),seo_title:text(b.seo_title,180),seo_description:text(b.seo_description,320)}
 if(type==='conversation'){const videoUrl=cleanText(b.video_url,1200);return{...common,guest_name:text(b.guest_name,160),guest_title:text(b.guest_title,200),subtitle:text(b.subtitle,300),short_description:text(b.short_description,700),description:text(b.description,30000)||'',category:text(b.category,100),topic:text(b.topic,100),video_url:videoUrl||null,media_source:source(videoUrl,cleanText(b.media_source,30)),thumbnail_url:text(b.thumbnail_url,1200),cover_url:text(b.cover_url,1200),recording_date:date(b.recording_date),duration_seconds:integer(b.duration_seconds),captions_url:text(b.captions_url,1200),transcript:text(b.transcript,50000),chapters:lines(b.chapters),related_links:lines(b.related_links)}}
 return{...common,subtitle:text(b.subtitle,300),excerpt:text(b.excerpt,1000),body:[{text:cleanText(b.body,50000)}],topic:text(b.topic,100),category:text(b.category,100),cover_url:text(b.cover_url,1200),pdf_url:text(b.pdf_url,1200),pdf_download_enabled:bool(b.pdf_download_enabled),audio_url:text(b.audio_url,1200),reading_minutes:integer(b.reading_minutes),audio_duration_seconds:integer(b.audio_duration_seconds),references_data:lines(b.references_data),footnotes:lines(b.footnotes)}
}
async function allowed(){return await hostAuthorized()}
export async function GET(req:NextRequest){if(!await allowed())return NextResponse.json({error:'Unauthorized'},{status:401,headers});if(!hasDatabase())return NextResponse.json({error:'Production database is not configured.'},{status:503,headers});const type=req.nextUrl.searchParams.get('type')==='paper'?'paper':'conversation',id=cleanText(req.nextUrl.searchParams.get('id'),100),table=type==='paper'?'papers':'conversations';const query=createAdminClient().from(table).select('*').order('updated_at',{ascending:false});const{data,error}=id?await query.eq('id',id).single():await query;if(error)return NextResponse.json({error:error.message},{status:500,headers});return NextResponse.json({items:id?[data]:data},{headers})}
export async function POST(req:NextRequest){if(!await allowed())return NextResponse.json({error:'Unauthorized'},{status:401,headers});if(!hasDatabase())return NextResponse.json({error:'Connect the production database before saving.'},{status:503,headers});try{const b=await req.json(),type=b.type==='paper'?'paper':'conversation',row=build(type,b);if(!row.title||!row.slug||!/^([a-z0-9]+-?)+$/.test(String(row.slug)))return NextResponse.json({error:'Title and a lowercase URL slug are required.'},{status:400,headers});if(type==='conversation'&&(!('guest_name'in row)||!row.guest_name))return NextResponse.json({error:'Guest name is required.'},{status:400,headers});if(type==='paper'&&(!('pdf_url'in row)||!row.pdf_url))return NextResponse.json({error:'Every paper requires a PDF.'},{status:400,headers});const db=createAdminClient();const result=type==='paper'?await db.from('papers').insert(row as never).select().single():await db.from('conversations').insert(row as never).select().single();const{data,error}=result;if(error)throw error;await db.from('audit_logs').insert({action:'content.create',entity_type:type,entity_id:data.id,new_value:data});return NextResponse.json({ok:true,item:data},{headers})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Content could not be saved.'},{status:500,headers})}}
export async function PATCH(req:NextRequest){if(!await allowed())return NextResponse.json({error:'Unauthorized'},{status:401,headers});if(!hasDatabase())return NextResponse.json({error:'Connect the production database before saving.'},{status:503,headers});try{const b=await req.json(),type=b.type==='paper'?'paper':'conversation',id=cleanText(b.id,100);if(!id)return NextResponse.json({error:'Content record is required.'},{status:400,headers});const db=createAdminClient(),table=type==='paper'?'papers':'conversations',{data:before,error:readError}=await db.from(table).select('*').eq('id',id).single();if(readError)throw readError;const row={...build(type,b),updated_at:new Date().toISOString()},{data,error}=await db.from(table).update(row).eq('id',id).select().single();if(error)throw error;await db.from('audit_logs').insert({action:'content.update',entity_type:type,entity_id:id,previous_value:before,new_value:data});return NextResponse.json({ok:true,item:data},{headers})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Changes could not be saved.'},{status:500,headers})}}
export async function DELETE(req:NextRequest){if(!await allowed())return NextResponse.json({error:'Unauthorized'},{status:401,headers});if(!hasDatabase())return NextResponse.json({error:'Database unavailable.'},{status:503,headers});const b=await req.json(),type=b.type==='paper'?'paper':'conversation',id=cleanText(b.id,100),table=type==='paper'?'papers':'conversations';if(!id)return NextResponse.json({error:'Content record is required.'},{status:400,headers});const db=createAdminClient(),{data:before}=await db.from(table).select('*').eq('id',id).single(),{error}=await db.from(table).delete().eq('id',id);if(error)return NextResponse.json({error:error.message},{status:500,headers});await db.from('audit_logs').insert({action:'content.delete',entity_type:type,entity_id:id,previous_value:before});return NextResponse.json({ok:true},{headers})}
