import { createClient } from '@/lib/supabase/server'
import { conversations as samplesConversations, papers as samplesPapers } from '@/lib/content'
import type { ContentStatus, Conversation, Paper } from '@/lib/types'

function configured(){return Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)}
function mapConversation(row:Record<string,unknown>):Conversation{return{id:String(row.id),slug:String(row.slug),title:String(row.title),guestName:String(row.guest_name||''),guestTitle:row.guest_title?String(row.guest_title):undefined,description:String(row.description||''),category:String(row.category||'Conversation'),publishedAt:String(row.published_at||row.created_at||new Date().toISOString()),duration:row.duration_seconds?`${Math.ceil(Number(row.duration_seconds)/60)} min`:'Duration pending',image:String(row.thumbnail_url||'/editorial/exchange.jpg'),videoUrl:row.video_url?String(row.video_url):undefined,transcript:row.transcript?String(row.transcript):undefined,views:Number(row.view_adjustment||0),reactions:0,commentsEnabled:row.comments_enabled!==false,reactionsEnabled:row.reactions_enabled!==false,status:String(row.status)as ContentStatus,sample:Boolean(row.is_sample)}}
function mapPaper(row:Record<string,unknown>):Paper{const body=Array.isArray(row.body)?row.body as Paper['body']:[{text:String(row.excerpt||'')}];return{id:String(row.id),slug:String(row.slug),title:String(row.title),subtitle:String(row.subtitle||''),excerpt:String(row.excerpt||''),topic:String(row.topic||'Paper'),publishedAt:String(row.published_at||row.created_at||new Date().toISOString()),readingTime:row.reading_minutes?`${row.reading_minutes} min read`:'Reading time pending',audioDuration:row.audio_duration_seconds?`${Math.ceil(Number(row.audio_duration_seconds)/60)} min audio`:undefined,image:String(row.cover_url||'/editorial/paper-study.jpg'),body,pdfUrl:row.pdf_url?String(row.pdf_url):undefined,pdfDownloadEnabled:Boolean(row.pdf_download_enabled),views:Number(row.view_adjustment||0),reactions:0,status:String(row.status)as ContentStatus,sample:Boolean(row.is_sample)}}
export async function getPublishedConversations(){if(!configured())return samplesConversations;try{const{data,error}=await(await createClient()).from('conversations').select('*').eq('status','published').lte('published_at',new Date().toISOString()).order('published_at',{ascending:false});if(error)throw error;return(data||[]).map(row=>mapConversation(row as Record<string,unknown>))}catch{return samplesConversations}}
export async function getPublishedPapers(){if(!configured())return samplesPapers;try{const{data,error}=await(await createClient()).from('papers').select('*').eq('status','published').lte('published_at',new Date().toISOString()).order('published_at',{ascending:false});if(error)throw error;return(data||[]).map(row=>mapPaper(row as Record<string,unknown>))}catch{return samplesPapers}}
export async function getConversation(slug:string){if(!configured())return samplesConversations.find(item=>item.slug===slug);try{const{data,error}=await(await createClient()).from('conversations').select('*').eq('slug',slug).eq('status','published').maybeSingle();if(error)throw error;return data?mapConversation(data as Record<string,unknown>):samplesConversations.find(item=>item.slug===slug)}catch{return samplesConversations.find(item=>item.slug===slug)}}
export async function getPaper(slug:string){if(!configured())return samplesPapers.find(item=>item.slug===slug);try{const{data,error}=await(await createClient()).from('papers').select('*').eq('slug',slug).eq('status','published').maybeSingle();if(error)throw error;return data?mapPaper(data as Record<string,unknown>):samplesPapers.find(item=>item.slug===slug)}catch{return samplesPapers.find(item=>item.slug===slug)}}
