'use client'
import{useEffect,useRef,type PointerEvent as ReactPointerEvent}from'react'
type Options={autoDegreesPerSecond?:number;initialYaw?:number;initialPitch?:number;minPitch?:number;maxPitch?:number;active?:boolean;reducedMotion?:boolean}
export function useSculptureRotation({autoDegreesPerSecond=18,initialYaw=-24,initialPitch=7,minPitch=-22,maxPitch=22,active=true,reducedMotion=false}:Options={}){
 const elementRef=useRef<HTMLDivElement>(null),yaw=useRef(initialYaw),pitch=useRef(initialPitch),velocity=useRef({x:0,y:0}),drag=useRef({active:false,id:-1,x:0,y:0,time:0,distance:0}),suppressClickUntil=useRef(0)
 const render=()=>{if(elementRef.current)elementRef.current.style.transform=`rotateX(${pitch.current.toFixed(2)}deg) rotateY(${yaw.current.toFixed(2)}deg)`}
 useEffect(()=>{render();let frame=0,last=performance.now();const tick=(now:number)=>{const dt=Math.min(40,now-last);last=now;if(active&&!drag.current.active&&!reducedMotion){yaw.current+=autoDegreesPerSecond*dt/1000+velocity.current.x*dt;pitch.current=Math.max(minPitch,Math.min(maxPitch,pitch.current+velocity.current.y*dt));const decay=Math.pow(.9,dt/16.67);velocity.current.x*=decay;velocity.current.y*=decay;render()}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[active,autoDegreesPerSecond,maxPitch,minPitch,reducedMotion])
 const onPointerDown=(event:ReactPointerEvent<HTMLDivElement>)=>{if(event.button!==0)return;event.currentTarget.setPointerCapture(event.pointerId);drag.current={active:true,id:event.pointerId,x:event.clientX,y:event.clientY,time:performance.now(),distance:0};velocity.current={x:0,y:0};event.currentTarget.classList.add('is-dragging')}
 const onPointerMove=(event:ReactPointerEvent<HTMLDivElement>)=>{if(!drag.current.active||drag.current.id!==event.pointerId)return;event.preventDefault();const now=performance.now(),dx=event.clientX-drag.current.x,dy=event.clientY-drag.current.y,dt=Math.max(8,now-drag.current.time);yaw.current+=dx*.32;pitch.current=Math.max(minPitch,Math.min(maxPitch,pitch.current-dy*.2));velocity.current={x:Math.max(-.16,Math.min(.16,dx*.32/dt)),y:Math.max(-.08,Math.min(.08,-dy*.2/dt))};drag.current.x=event.clientX;drag.current.y=event.clientY;drag.current.time=now;drag.current.distance+=Math.hypot(dx,dy);render()}
 const release=(event:ReactPointerEvent<HTMLDivElement>)=>{if(!drag.current.active||drag.current.id!==event.pointerId)return;if(drag.current.distance>7)suppressClickUntil.current=performance.now()+350;drag.current.active=false;event.currentTarget.classList.remove('is-dragging');if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId)}
 return{elementRef,handlers:{onPointerDown,onPointerMove,onPointerUp:release,onPointerCancel:release},consumeDrag:()=>performance.now()<suppressClickUntil.current}
}
