create extension if not exists pgcrypto;
create extension if not exists citext;

create type content_status as enum ('draft','scheduled','published','unpublished','archived');
create type content_kind as enum ('conversation','paper');

create table host_users(id uuid primary key default gen_random_uuid(), email text unique not null, role text not null default 'host', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table categories(id uuid primary key default gen_random_uuid(), name text unique not null, slug text unique not null, kind content_kind, created_at timestamptz not null default now());
create table conversations(id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, guest_name text not null, guest_title text, description text not null default '', category text, published_at timestamptz, scheduled_for timestamptz, duration_seconds integer check(duration_seconds is null or duration_seconds>=0), status content_status not null default 'draft', media_source text check(media_source in ('upload','supabase','youtube','vimeo','drive')), video_url text, thumbnail_url text, captions_url text, transcript text, chapters jsonb not null default '[]', related_links jsonb not null default '[]', comments_enabled boolean not null default true, reactions_enabled boolean not null default true, public_view_mode text not null default 'opens', manual_view_override bigint, view_adjustment bigint not null default 0, is_sample boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table conversation_chapters(id uuid primary key default gen_random_uuid(), conversation_id uuid not null references conversations on delete cascade, title text not null, starts_at_seconds integer not null check(starts_at_seconds>=0), position integer not null default 0);
create table papers(id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, subtitle text, excerpt text, topic text, body jsonb not null default '[]', published_at timestamptz, scheduled_for timestamptz, reading_minutes integer check(reading_minutes is null or reading_minutes>0), status content_status not null default 'draft', cover_url text, pdf_url text, pdf_download_enabled boolean not null default false, audio_url text, audio_duration_seconds integer, references_data jsonb not null default '[]', comments_enabled boolean not null default true, reactions_enabled boolean not null default true, public_view_mode text not null default 'opens', manual_view_override bigint, view_adjustment bigint not null default 0, is_sample boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table media_assets(id uuid primary key default gen_random_uuid(), storage_path text unique not null, public_url text, mime_type text not null, byte_size bigint not null check(byte_size>0), alt_text text, caption text, created_at timestamptz not null default now());
create table reaction_types(id uuid primary key default gen_random_uuid(), name text unique not null, slug text unique not null, icon_svg text not null, position integer not null default 0, enabled boolean not null default true, created_at timestamptz not null default now());
create table reactions(id uuid primary key default gen_random_uuid(), content_id text not null, content_type content_kind not null, reaction_type text not null, visitor_id text not null, created_at timestamptz not null default now(), unique(content_id,visitor_id,reaction_type));
create table comments(id uuid primary key default gen_random_uuid(), content_id text not null, content_type content_kind not null, anonymous_name text not null, body text not null check(length(body) between 2 and 1800), parent_id uuid references comments on delete cascade, is_pinned boolean not null default false, is_hidden boolean not null default false, is_official boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table comment_reports(id uuid primary key default gen_random_uuid(), comment_id uuid not null references comments on delete cascade, reason text, visitor_id text, status text not null default 'new' check(status in ('new','reviewed','resolved')), created_at timestamptz not null default now());
create table subscribers(id uuid primary key default gen_random_uuid(), email citext unique not null, name text, age_range text, gender text, country text, consent_status boolean not null check(consent_status=true), consented_at timestamptz not null, joined_at timestamptz not null default now(), unsubscribed_at timestamptz);
create table questions(id uuid primary key default gen_random_uuid(), email citext not null, name text, organization text, category text, message text not null, status text not null default 'new' check(status in ('new','reviewed','answered','archived')), private_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table site_settings(key text primary key, value jsonb not null, updated_at timestamptz not null default now(), updated_by uuid references host_users on delete set null);
create table analytics_events(id bigint generated always as identity primary key, event_type text not null, page_path text, content_id text, content_type content_kind, anonymous_session text not null, country text, referrer text, created_at timestamptz not null default now());
create table statistic_adjustments(id uuid primary key default gen_random_uuid(), statistic_key text unique not null, adjustment bigint not null default 0, manual_override bigint, updated_at timestamptz not null default now(), updated_by uuid references host_users on delete set null);
create table notification_campaigns(id uuid primary key default gen_random_uuid(), subject text not null, preview_text text, content_kind content_kind, content_id text, status text not null default 'draft' check(status in ('draft','approved','sending','sent','failed')), recipient_count integer not null default 0, sent_at timestamptz, created_at timestamptz not null default now());
create table audit_logs(id bigint generated always as identity primary key, host_user_id uuid references host_users on delete set null, action text not null, entity_type text not null, entity_id text, previous_value jsonb, new_value jsonb, details jsonb, created_at timestamptz not null default now());

create index conversations_public on conversations(status,published_at desc);create index papers_public on papers(status,published_at desc);create index comments_content on comments(content_id,is_hidden,is_pinned,created_at);create index analytics_time on analytics_events(created_at desc);create index analytics_content on analytics_events(content_id,event_type);create index questions_status on questions(status,created_at desc);create index subscribers_active on subscribers(unsubscribed_at) where unsubscribed_at is null;

alter table conversations enable row level security;alter table papers enable row level security;alter table categories enable row level security;alter table reaction_types enable row level security;alter table reactions enable row level security;alter table comments enable row level security;alter table subscribers enable row level security;alter table questions enable row level security;alter table site_settings enable row level security;alter table analytics_events enable row level security;
create policy public_conversations on conversations for select using(status='published' and coalesce(published_at,now())<=now());create policy public_papers on papers for select using(status='published' and coalesce(published_at,now())<=now());create policy public_categories on categories for select using(true);create policy public_reaction_types on reaction_types for select using(enabled);create policy public_comments on comments for select using(not is_hidden);create policy public_settings on site_settings for select using(true);

insert into reaction_types(name,slug,icon_svg,position) values('Appreciate','appreciate','M6 13h12M12 7v12',1),('Insightful','insightful','M9 18h6M10 22h4M8 11a4 4 0 1 1 8 0c0 2-1 3-2 4H10c-1-1-2-2-2-4Z',2),('Powerful','powerful','m13 2-9 12h7l-1 8 9-12h-7z',3) on conflict do nothing;
